n_jobs: 8
stage: 0
samplerate: 16000

output_dir: /disks/disk1/scornell/FastMSS/ami-synth-ihm
hydra: # overrides standard hydra output dir
  run:
    dir: ${output_dir}

n_meetings: 5000
min_max_spk: [2, 5] # min max speakers.
save_anechoic: True # save also anechoic
save_spk: True # save each speaker stream

duration: 35
manifest_prefix: ami-ihm
manifest_dir: /disks/disk1/scornell/AMI
dset_splits:
  - train
split_fa_factor: 0.2
max_utt_duration: 60
min_utt_duration: 0.3
min_spk_utt: 5
use_markov: True

base_gain: [-35, -8]
rel_gain: [-12, +5]
add_noise: True
noise_rel_gain: [-6, 8]
speed_perturb: False # this makes generation reaaally slow.
speed_perturb_range: [0.95, 1.05]
use_fir: False

# these will be parsed and sampled randomly.
# probably good to sample based on length of each file.
# noise_sample_weighted: True
noise_folders:
  - /disks/disk1/scornell/FastMSS/wham_noise_16khz

filter_noise_len: 20 # remove shorter than 20 seconds

reverberate: True
n_rirs: 1000
n_pos_rirs: 50
rt60: [0.1, 0.7]
room_sz: [5, 10]
room_ceiling: [3, 5]
delta_dist: 0.5  # min distance between walls and among speakers
use_rand_ism: False
rand_disp: 0.0 # if save anechoic this should be 0.0 probably

save_cutset: True
drop_without_align: True


#mic_type: circular_array
# todo add multichannel.
#circular_array: # match AMI
#  diameter: 0.08
#  n_mics: 8
# linear array
# displaced array
# add support also for hrtf ? it would be cool !
# doa too would be cool.

# add support to fit real meetings HMM stats from supervisions.
