n_jobs: 8
stage: 0
samplerate: 16000

output_dir: /raid/users/popcornell/FastMSS/generated/train
hydra: # overrides standard hydra output dir
  run:
    dir: ${output_dir}

n_meetings: 5000
min_max_spk: [2, 8] # min max speakers.
max_concurrent_speakers: 3 # max number of speakers talking simultaneously (set to null to disable)
save_anechoic: True # save also anechoic
save_spk: True # save each speaker stream

duration: 120
manifest_prefix: librispeech
librispeech_dir: /raid/users/popcornell/LibriSpeech
librispeech_align: /raid/users/popcornell/FastMSS/LibriSpeech/
dset_splits:
  - train-clean-100
split_fa_factor: 0.25
max_utt_duration: 60
min_utt_duration: 0.0
min_spk_utt: 5
use_markov: True

base_gain: [-35, -8]
rel_gain: [-12, +5]
add_noise: True
noise_rel_gain: [-24, 6]
multi_noise_sampling: True # sample multiple noise files and concatenate with cross-fading
speed_perturb: False # this makes generation reaaally slow.
speed_perturb_range: [0.95, 1.05]
use_fir: False

# these will be parsed and sampled randomly.
# probably good to sample based on length of each file.
# noise_sample_weighted: True
noise_folders:
  - /raid/users/popcornell/FastMSS/high_res_wham_16kHz

noise_filename_pattern: null # regex pattern to filter noise files by name (e.g., "example.*\.wav" or "^noise_.*")
filter_noise_len: 2.0 # remove shorter than 20 seconds

reverberate: True
n_rirs: 1000
n_pos_rirs: 50
rt60: [0.1, 0.7]
room_sz: [5, 10]
room_ceiling: [3, 5]
delta_dist: 0.5  # min distance between walls and among speakers
use_rand_ism: False
rand_disp: 0.0 # if save anechoic this should be 0.0 probably

save_cutset: True
drop_without_align: True


mic_type: single
# todo add multichannel.
# circular_array
# linear array
# displaced array
# add support also for hrtf ? it would be cool !
# doa too would be cool.

# add support to fit real meetings HMM stats from supervisions.
