n_jobs: 8
stage: 0
samplerate: 16000

output_dir: /Users/samco/Datasets/synth-oto
hydra: # overrides standard hydra output dir
  run:
    dir: ${output_dir}

n_meetings: 15
min_max_spk: [2, 8] # min max speakers.
max_concurrent_speakers: 2 # max number of speakers talking simultaneously (set to null to disable)
save_anechoic: False # save also anechoic
save_spk: False # save each speaker stream

duration: 60
manifest_prefix:
manifest_dir: /Users/samco/Datasets/OtoDuplexCleaned/otoSpeech-full-duplex-processed-141h/lhotse_manifests
dset_splits:
max_utt_duration: 60
min_utt_duration: 1.0
min_spk_utt: 5
use_markov: True

base_gain: [-35, -8]
rel_gain: [-12, +5]
add_noise: True
noise_rel_gain: [-24, 8]
speed_perturb: False # this makes generation reaaally slow.
speed_perturb_range: [0.95, 1.05]
use_fir: False

# these will be parsed and sampled randomly.
# probably good to sample based on length of each file.
# noise_sample_weighted: True
noise_folders:
  - /Users/samco/Datasets/BFND/

noise_filename_pattern: 'example\d+\.wav' # regex pattern to filter noise files by name (e.g., "example.*\.wav" or "^noise_.*")
filter_noise_len: 2.0 # remove shorter than 20 seconds

#filter_noise_len: 20 # remove shorter than 20 seconds

reverberate: True
n_rirs: 20
n_pos_rirs: 50
rt60: [0.1, 0.7]
room_sz: [5, 10]
room_ceiling: [3, 5]
delta_dist: 0.5  # min distance between walls and among speakers
use_rand_ism: False
rand_disp: 0.0 # if save anechoic this should be 0.0 probably
max_position_change: 0.5  # meters - max distance speaker can move per utterance

save_cutset: True
drop_without_align: True


mic_type: single
# todo add multichannel.
circular: # match AMI
  diameter: [0.08, 0.085]
  n_mics: 8
  center_mic: False
# linear array ?
# displaced ad-hoc array
# echi (over the ear)
# clarity.
# easycom hrtf too
# random array (linear, circular)
# add support also for hrtf ? it would be cool ! targeting CHiME-9 and EasyCom and what else ?
# doa too would be cool.
# for diffuse noise I need to save some room parameters. I might also save src positions too.

# add support to fit real meetings HMM stats from supervisions.
