n_jobs: 8
stage: 0
samplerate: 16000

output_dir: ${oc.env:SIM_OUT_ROOT}/nsf/nsf_estimate_boosted
hydra: # overrides standard hydra output dir
  run:
    dir: ${output_dir}

n_meetings: 7500
min_max_spk: [2, 5] # min max speakers.
max_concurrent_speakers: 4 # max number of speakers talking simultaneously (set to null to disable)
save_anechoic: False # save also anechoic
save_spk: False # save each speaker stream

duration: 240
manifest_prefix: notsofar1_ihm
manifest_dir: ${oc.env:MANIFEST_DIR}/notsofar1
dset_splits:
  - train_set_240825.1_train
split_fa_factor: 0.2
max_utt_duration: 20
min_utt_duration: 0.0
min_spk_utt: 5
use_markov: False

base_gain: [-35, -8]
rel_gain: [-12, +5]
add_noise: False
noise_rel_gain: [-24, 8]
speed_perturb: False # this makes generation reaaally slow.
speed_perturb_range: [0.95, 1.05]
use_fir: False

# these will be parsed and sampled randomly.
# probably good to sample based on length of each file.
# noise_sample_weighted: True
noise_folders: null

filter_noise_len: 20 # remove shorter than 20 seconds

reverberate: False
n_rirs: 0
n_pos_rirs: 50
rt60: [0.1, 0.7]
room_sz: [5, 10]
room_ceiling: [3, 5]
delta_dist: 0.5  # min distance between walls and among speakers
use_rand_ism: False
rand_disp: 0.0 # if save anechoic this should be 0.0 probably

save_cutset: True
drop_without_align: True

mic_type: single
# todo add multichannel.
circular: # match AMI
  diameter: [0.08, 0.085]
  n_mics: 8
  center_mic: False

hmm_fit_transitions_to: ${oc.env:MANIFEST_DIR}/notsofar1/notsofar1_sdm_train_set_240825.1_train_cutset.jsonl.gz
boost_overlap_factor: 2.0